import './globals.css';
import '../css/_variables.css';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { CartProvider } from '@/lib/context/CartContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
